 - name: restart xinetd
   service:
     name: xinetd
     state: restarted

 - name: restart apache
   service:
     name: httpd
     state: restarted

 - name: restart dhcpd
   service:
     name: dhcpd
     state: restarted
